[tool.black]
line-length = 100
target-version = ["py311"]
extend-exclude = "/(static|templates|migrations|node_modules)/"

[tool.isort]
profile = "black"
line_length = 100
skip = ["static", "templates", "node_modules", "migrations"]
